name: OneLife
version: '2-Beta-20'
main: xyz.acyber.oneLife.OneLifePlugin
api-version: '1.21.10'
dependencies:
  server:
    # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true