name: OneLife
version: '2-Beta-6'
main: xyz.acyber.oneLife.Main
api-version: '1.21.7'
dependencies:
  server:
    # Add a required "RequiredPlugin" dependency, which will load AFTER your plugin.
    LuckPerms:
      load: BEFORE
      required: true
      # This means that your plugin will not have access to their classpath
      join-classpath: true